### ISSUE TITLE
install issue?

### ISSUE THREAD

**Issue by kirchaj** [dwijitsolutions/laraadmin#1]
I ran the install as described in the instructions with a mysql database and received this error

[Exception]
  LAInstall::handle Unable to install : Unable to generate migration for Students : Invalid view_column_name. 'This should be database friendly lowercase name.'

**Comment by gdbhosale** [comment]
Hello kirchaj,

You need to provide your "view column name" in migrations.
It is necessary for datatables show item link.
Generally we use that column as "title", "name", "username"

**Comment by kirchaj** [comment]
where is that done.  All I am doing is running the install as below

C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin>php artisan la:install                                                          
LaraAdmin installation started...                                                                                                      
from: C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor/dwij/laraadmin/src/Installs to: C:\BitNami\wampstack-5.5.28-0\apach
                                                                                                                                       
 This process may change/append to following of your existing project files:                                                           
                                                                                                                                       
         app/Http/routes.php                                                                                                           
         app/User.php                                                                                                                  
         database/migrations/2014_10_12_000000_create_users_table.php                                                                  
         gulpfile.js                                                                                                                   
                                                                                                                                       
 Please take backup or use git. Do you wish to continue ? (yes/no) [yes]:                                                              
 >                                                                                                                                     
                                                                                                                                       
                                                                                                                                       
Generating Controllers...                                                                                                              
Generating Models...                                                                                                                   
Appending routes...                                                                                                                    
Generating Config...                                                                                                                   
Generating LaraAdmin Public Assets...                                                                                                  
Generating migrations...                                                                                                               
Generating resources: assets + views...                                                                                                
Generating Utilities...                                                                                                                
Running migrations...                                                                                                                  
LAInstall::handle exception: exception 'Exception' with message 'Unable to generate migration for Students : Invalid view_column_name. 
owercase name.'' in C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\dwij\laraadmin\src\Models\Module.php:35              
Stack trace:

**Comment by gdbhosale** [comment]
Hello kirchaj,

I understood your concern.

This bug is fixed in version 1.0.5
Please update the package and check again.
This will change your earlier file structure a little.
Have a backup before trying.
`composer update dwij/laraadmin`

Best Regards,

**Comment by kirchaj** [comment]
Thanks.  I did the update and the problem still existed.  I deleted the migrations and ran again.  It then produced these errors.

Generating Controllers...                                                                                                                                  
Generating Models...                                                                                                                                       
Appending routes...                                                                                                                                        
Generating Config...                                                                                                                                       
Generating LaraAdmin Public Assets...                                                                                                                      
Generating migrations...                                                                                                                                   
Generating resources: assets + views...                                                                                                                    
Generating Utilities...                                                                                                                                    
Running migrations...                                                                                                                                      
Nothing to migrate.                                                                                                                                        
Creating Super Admin Role...                                                                                                                               
LAInstall::handle exception: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hod' in 'field list            
'' in C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\laravel\framework\src\Illuminate\Database\Connection.php:441                           
Stack trace:                                                                                                                                               
#0 C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\laravel\framework\src\Illuminate\Database\Connection.php(441): PDO->prepare('i            
nsert into `de...')                                                                                                                                        
#1 C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\laravel\framework\src\Illuminate\Database\Connection.php(706): Illuminate\Data            
base\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `de...', Array)                                   
#2 C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\laravel\framework\src\Illuminate\Database\Connection.php(669): Illuminate\Data            
base\Connection->runQueryCallback('insert into `de...', Array, Object(Closure))                                                                            
#3 C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\laravel\framework\src\Illuminate\Database\Connection.php(442): Illuminate\Data            
base\Connection->run('insert into `de...', Array, Object(Closure))                                                                                         
#4 C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\laravel\framework\src\Illuminate\Database\Connection.php(398): Illuminate\Data            
base\Connection->statement('insert into `de...', Array)                                                                                                    
#5 C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2039): Illuminate\            
Database\Connection->insert('insert into `de...', Array)                                                                                                   
#6 C:\BitNami\wampstack-5.5.28-0\apache2\htdocs\laraadmin\vendor\dwij\laraadmin\src\Commands\LAInstall.php(113): Illuminate\Database\Query\Buil            
der->insert(Array)

**Comment by gdbhosale** [comment]
Hi kirchaj,

You are getting this error because of old database table for departments.

Please take backup of database and run following commands:

`composer dump-autoload`
`php artisan migrate:refresh`

This will definitely solve this issue.

I am very sorry for your time.
But it gives me inspiration to make this project better.

Thanks for your support.

I am reopening this issue. Let me know soon, if you succeed with installation.

Best Regards,

**Comment by gdbhosale** [comment]
Issues successfully resolved in version 1.0.10

**Comment by rafasottam** [comment]
$ php artisan migrate:refresh
Rolled back: 2016_10_06_115413_create_la_configs_table
Rolled back: 2016_09_22_110008_role_module_table
Rolled back: 2016_09_22_105958_role_module_fields_table
Rolled back: 2016_09_10_163520_create_permission_role_table
Rolled back: 2016_09_10_163337_create_permissions_table
Rolled back: 2016_07_07_134058_create_menus_table
Rolled back: 2016_07_07_134058_create_backups_table
Rolled back: 2016_07_06_1406376_create_industry_types_table
Rolled back: 2016_07_06_140637_create_organizations_table
Rolled back: 2016_07_05_115343_create_role_user_table
Rolled back: 2016_05_26_064446_create_roles_table
Rolled back: 2016_05_26_064007_create_employees_table
Rolled back: 2016_05_26_064006_create_departments_table
Rolled back: 2014_12_01_000000_create_uploads_table
Rolled back: 2014_10_12_100000_create_password_resets_table
Rolled back: 2014_10_12_000000_create_users_table
Rolled back: 2014_05_26_060000_create_module_fields_table
Rolled back: 2014_05_26_055000_create_module_field_types_table
Rolled back: 2014_05_26_050000_create_modules_table


  [ErrorException]
  Undefined offset: 0

**Comment by azarzaza** [comment]
please install it properly check the requirement of laraadmin

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
1. when i run php artisan la:install  then why below bug come?

[Exception]                                                                  
  LAInstall::handle Unable to install : unlink(/home/pankaj/Desktop/laraadmin  
  /app/Http/Controllers/LA/BackupsController.php): Permission denied 


2. when i have run php artisan migrate:refresh and then  below why bug comming ?
  [ErrorException]                         
  Invalid argument supplied for foreach()

**Comment by azarzaza** [comment]
please install the Lara admin properly
once installed the Lara admin don't need to delete the module or table
manually because it will affect the whole code

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
Azarzaza sir, i again install the laraadmin but this error comes?
la1$ php artisan serve
PHP Fatal error:  Class 'Dwij\Laraadmin\LAProvider' not found in /home/pankaj/la1/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

but i defined the class   Dwij\Laraadmin\LAProvider::class,  in config/app.php

**Comment by azarzaza** [comment]
here my its working fine
if u don't install properly then you will face like this type of error
 your installation not properly done due to the internet connections
please install a fresh one then u check it

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
Thank you soo much sir, now its fine but when i hits the localhost:8000/admin then again bug 
BadMethodCallException in Repository.php line 367:
This cache store does not support tagging.

**Comment by azarzaza** [comment]
Try to config cache

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
Here my its working fine, Thanks for your support me

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
when creating module  
Loyalties
Model doesn't exists Items
why this is came?
and also in la editor menu  this bug is come
invalidArgumentException in FileViewFinder.php line 137:
View [la.editor.index] not found.
please help me

**Comment by mahfoudfx** [comment]
First, I want to thank you for the geat project.
I am under Windows 10 1704 x64, with Laragon Full 3.13. php 7.1.7 vc14, Apache httpd 2.4.27.
I am following installation instructions http://laraadmin.com/docs/1.0 .
At the 5th step of installing LaraAdmin Package, when executing this command : 
"php artisan la:install" I get the following errors:
C:\laragon\www\la1>php artisan la:install
[37;41m                                                                  [39;49m
[37;41m  [Symfony\Component\Console\Exception\CommandNotFoundException]  [39;49m
[37;41m  There are no commands defined in the "la" namespace.            [39;49m
[37;41m                                                                  [39;49m
Thanks for your help.

**Comment by rushilprajapati** [comment]
#271

**Comment by rushilprajapati** [comment]
- [ ]
