### ISSUE TITLE
Scrollbars are showing off and on when hovering on the set view column icon

### ISSUE THREAD

**Issue by mgazelle** [dwijitsolutions/laraadmin#39]
Scrollbars are showing off and on when hovering on the set view column icon due to properties set dynamically

would be nice to just add an alt to the icons and remove the dynamically added attribute

**Comment by gdbhosale** [comment]
Fixed.

**Comment by mgazelle** [comment]
Is still not working with the latest commit. Scrollbars are still getting off and on.

A solution to the issue is to remove the title tag of the set column icon

**Comment by gdbhosale** [comment]
Check now.
